{
 "title": "Spider Monitor Platform",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project_Status",
    "label": "Project_Status",
    "query": "select  case  when count(1)>0 then 'Runing' else 'StandBy' end from spider_task_monitor  where project_name='$Project' and status=1"
   },
   {
    "name": "Project",
    "label": "Project",
    "query": "select distinct project_name from spider_task_monitor"
   },
   {
    "name": "Spider",
    "label": "Spider",
    "query": "select distinct spider_name from spider_task_monitor where project_name='$Project'"
   },
   {
    "name": "Period_Job_Id",
    "label": "Period_Job_Id",
    "query": "select job_instance_id  from spider_task_monitor where project_name='$Project' and spider_name= '$Spider'"
   },
   {
    "name": "Spider_Task_Id",
    "label": "Spider_Task_Id",
    "query": "select distinct task_instance_id from spider_task_monitor where project_name='$Project' and spider_name in ('$Spider') and job_instance_id = '$Period_Job_Id'"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Project in  Running",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \r\ncount(distinct project_name)\r\nFROM spider_task_monitor\r\nWHERE \r\n$__timeFilter(create_time) and project_name='$Project' and\r\nstatus =1\r\n"
    }
   ]
  },
  {
   "title": "Node Monitor",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\nexecute_ip as 'node',\r\ncase when status =1 then count(1) end as 'task-in-running'\r\nFROM spider_task_monitor\r\nwhere $__timeFilter(create_time) and project_name='$Project'\r\ngroup by execute_ip"
    }
   ]
  },
  { "title": "$Project : $Project_Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Spider Monitor",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\nproject_name,\r\nspider_name,\r\ncase when status=0 then count(1) end as 'pendding',\r\ncase when status=1 then count(1) end as 'running',\r\ncase when status=2 then count(1) end as 'stop',\r\ncase when status=3 then count(1) end as 'cancel',\r\ncase when status=4 then count(1) end as 'finish'\r\nFROM spider_task_monitor\r\nwhere $__timeFilter(create_time) \r\n  and project_name='$Project' \r\n  and spider_name='$Spider' \r\n  and job_instance_id = '$Period_Job_Id'\r\ngroup by project_name,spider_name"
    }
   ]
  },
  {
   "title": "Project Node Monitor",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\nspider_name,\r\njob_instance_id,\r\ntask_instance_id,\r\nexecute_ip as 'node',\r\ncase when status =1 then count(1) end as 'task-in-running'\r\nFROM spider_task_monitor\r\nwhere $__timeFilter(create_time) and project_name='$Project' and job_instance_id='$Period_Job_Id'\r\ngroup by 1,2,3,4"
    }
   ]
  },
  { "title": "Spider Task Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Task Request Monitor",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ta.spider_name,\r\n\tta.job_instance_id,\r\n\tta.task_instance_id,\r\n\tta.request,\r\n\tta.response,\r\n\tta.filtered_request,\r\n\tta.crawled_pages,\r\n\tta.status_200,\r\n\tta.status_other,\r\n\tta.redirect,\r\n\tta.retry,\r\n\tta.ignored\r\nFROM\r\n\tspider_crawl_monitor ta\r\n\tJOIN ( SELECT job_instance_id, task_instance_id, max( stat_time ) AS 'now' FROM spider_crawl_monitor GROUP BY job_instance_id, task_instance_id ) tb ON ta.job_instance_id = tb.job_instance_id \r\n\tAND ta.task_instance_id = tb.task_instance_id \r\n\tAND ta.stat_time = tb.now\r\n\tjoin spider_task_monitor tc\r\n\ton ta.task_instance_id= tc.task_instance_id\r\nWHERE\r\n  $__timeFilter(ta.stat_time)\r\n  and project_name ='$Project'\r\n  and ta.spider_name = '$Spider'\r\n  and ta.task_instance_id in ($Spider_Task_Id)\r\n-- ORDER BY stat_time\r\n"
    }
   ]
  },
  {
   "title": "Spider Response Parse Monitor",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ta.spider_name,\r\n\tta.job_instance_id,\r\n\tta.task_instance_id,\r\n\tta.scraped_items,\r\n\tta.critical,\r\n\tta.error,\r\n\tta.warning,\r\n\tta.remark\r\n\t\r\nFROM\r\n\tspider_crawl_monitor ta\r\n\tJOIN ( SELECT job_instance_id, task_instance_id, max( stat_time ) AS 'now' FROM spider_crawl_monitor GROUP BY job_instance_id, task_instance_id ) tb ON ta.job_instance_id = tb.job_instance_id \r\n\tAND ta.task_instance_id = tb.task_instance_id \r\n\tAND ta.stat_time = tb.now\r\n\tjoin spider_task_monitor tc\r\n\ton ta.task_instance_id= tc.task_instance_id\r\nWHERE\r\n  $__timeFilter(stat_time)\r\n  and project_name ='$Project'\r\n  and ta.spider_name = '$Spider'\r\n  and ta.task_instance_id in ($Spider_Task_Id)\r\n-- ORDER BY stat_time\r\n"
    }
   ]
  },
  {
   "title": "Spider Crawl Monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  stat_time AS \"time\",\r\n  -- task_instance_id as metric,\r\n  round(request*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'request_avg',\r\n  round(response*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'response_avg',\r\n  round(crawled_pages*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'crawled_pages_avg',\r\n  round(scraped_items*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'scraped_items_avg'\r\nFROM spider_crawl_monitor\r\nWHERE\r\n  $__timeFilter(stat_time) \r\n  and task_instance_id in ($Spider_Task_Id)\r\nORDER BY stat_time"
    }
   ]
  },
  {
   "title": "Spider Crawl Monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  stat_time AS \"time\",\r\n  -- task_instance_id as metric,\r\n  round(request*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'request_avg',\r\n  round(response*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'response_avg',\r\n  round(crawled_pages*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'crawled_pages_avg',\r\n  round(scraped_items*60/TIMESTAMPDIFF(second,create_time,stat_time),0) as 'scraped_items_avg'\r\nFROM spider_crawl_monitor\r\nWHERE\r\n  $__timeFilter(stat_time)\r\n  and task_instance_id in ($Spider_Task_Id)\r\nORDER BY stat_time"
    }
   ]
  }
 ]
}